#spring
spring:
#  datasource:
#    url: jdbc:mysql://43.202.68.211:3306/sorhy?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:h2:tcp://localhost/~/sorhy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #h2 설정
      ddl-auto: create

      #mysql 설정
#      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 20MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

#cloud
cloud:
  aws:
    s3:
      bucket: ssafy-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIAW6YCIM2HS7A3RE2N
      secret-key: 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


notification:
  mattermost:
    enabled: true # mmSender를 사용할 지 여부, false면 알림이 오지 않는다
    webhook-url: https://meeting.ssafy.com/hooks/dbyghor55tr5mqcrx88oddop6w
    channel: # 기본 설정한 채널이 아닌 다른 채널로 보내고 싶을 때 기입한다
    pretext: # attachments의 상단에 나오게 되는 일반 텍스트 문자
    color : # attachment에 왼쪽 사이드 컬러. default=red
    author-name: # attachment의 상단에 나오는 이름
    author-icon: # author-icon 왼쪽에 나올 아이콘의 url링크
    footer: # attachment에 하단에 나올 부분.z default=현재 시간
# jwt

jwt:
  secret: akjldfadlksjflkflkasndf!@$!@$slakdfklasdnfasi;ofnsad;ifasndf;lsdfknfdslkf
